export const meta = {
 name:"block-01-revb",
 description:"Execute Rev B promptly using the existing Astra/Sol/Kimi/Sonnet design, including Track B and Annex A",
 phases:[{title:"Freeze Rev B delta"},{title:"Build and acquire inputs"},{title:"Verify"},{title:"Execute Rev B"},{title:"Final audit"}]
};
const common=`Operate in ${args.workspace} (use this explicit absolute path; verify cwd). Read REVB_REQUIREMENTS.md, the authoritative summary of user's Rev B plus Annex A. PROTOCOL.md is historical Rev A, now superseded; do not apply its N or scope. User explicitly says run B as soon as possible with same workflow design; no busywork. No corpus was generated or scored under Rev A (only analytical tests and host storage probe). Reuse DESIGN.md and partial C++ engine, avoid redoing architecture. No agent spawning. No deployments/restarts. Keep source here and final artifacts at ${args.storage}. Model allocations are fixed. Freeze operational details before experimental measurement, never tune from results. Ordinary deterministic implementation fixtures are allowed after freeze. Report actual incomplete scope/resource blocks honestly. `;
phase("Freeze Rev B delta");
const freeze=await agent(common+`You own ONLY the most complicated delta: adapting exact bounded-RAM engine design to alphabet256 and12 checkpoints, plus unambiguous preregistration. Reuse existing Astra DESIGN.md, do not rewrite it wholesale. Write REVB_PROTOCOL.md and machine-readable freeze manifest for Track A (90 surfaces) and evaluation/Annex conventions now, BEFORE sampling. Reuse existing PRNG and lag-copy kernels, extend G3 block to length d+1 with controller16..23, d-1 fillers0..15, agreeing24..31, paired G5 short lag2/G6 lagd; entropy proof same. Startup semantics explicit. Resolve saturation from Annex's first increment<0.01; explicitly label this operational convention, no automatic sustained plateau interpretation. Use mean surfaces for between-corpus/seed comparisons, sample std, strict tie handling for unique largest increment, zero denominators undefined, negatives retained. Annex cost use declared empirical conditional ML checkpoint code reference if feasible; label KT-minus-ML descriptive redundancy, NOT uniquely pure learning cost. Record occupancy empirical visitation mass, n finite differences and whitespace attribution conventions. Track B source metadata freeze is owned by Sonnet before any B measurement; do not wait for sources here. Byte alphabet chosen by explicit sidecar not inferred. Identify minimal engine modifications (80->128bit context, dense depth adaptation, exact disk state) in REVB_DELTA.md. Do not generate/measure data; return concise implementation instructions.`,{model:"cpa/gpt-6-astra",reasoningLevel:"high",label:"Astra: freeze surface and byte-engine delta"});
phase("Build and acquire inputs");
const built=await parallel([
 ()=>agent(common+`Own core C++ engine/generators/Python API/build/core tests. Read REVB_PROTOCOL.md and REVB_DELTA.md; finish existing partial engine rather than start over. Implement availability(corpus_path,k_max,checkpoints)->surface, all k/checkpoints one pass, explicit32/256 metadata, fixed bounded cache and exact disk counts, deterministic order. Ninety Track A surfaces required; do not duplicate paired G5 runs silently (reuse identical outputs only with explicit provenance). Instrument Annex checkpoint L, per-symbol Track A losses, increments later, occupancy and KT-versus-declared-ML reference if feasible, B whitespace attribution. Freeze generator implementation/PRNG hashes before generator samples. Build and run focused reference/forced-spill tests, then write CORE_HANDOFF.md with exact CLI/API commands and JSON schema. No full production run yet, audit next; don't wait for Track B to implement. Do not own Track B source/ingestion files. ${freeze}`,{model:"cpa/gpt-5.6-sol",reasoningLevel:"high",label:"Sol: surface engine and generators"}),
 ()=>agent(common+`Own Track B acquisition/ingestion and reporting harness (not core code). Work concurrently with core. Source exact public English Wikipedia prose, single-language source code, English CHILDES adult child-directed speech, >=5*2^23 eligible bytes each; use live web_search for public sources and cite links. No substitutes/padding/duplicate draws or inclusion of child utterances to inflate CHILDES. Freeze sources/versions/licenses, extraction policy, disjoint draw algorithm, B1-derived B4 sentence shuffle and B5 within-sentence word shuffle preserving byte length, tokenizer/whitespace/seeds BEFORE measurement. Download/extract using deterministic declared policy, checksums/provenance; no result-driven source choices. If CHILDES eligibility/volume/public access is inadequate report concrete blocker promptly; keep other runs ready. Build internal experiment/report scripts or planning stub until CORE_HANDOFF exists; coordinate through files not wait loops. Need90A+25B runs,12x17 surfaces, 10 strict predictions/3 computed gates + Annex conditional interpretation, spread, saved L and Annex arrays, cost versus n/k/alphabet and2^30 extrapolation. No cross-track comparisons. REVB_PROTOCOL definitions bind. Keep SOURCES.md/TRACK_B_HANDOFF.md and runnable ingestion commands. No full KT experiment yet. Don't print raw personal transcript text. ${freeze}`,{model:"claude-bridge/claude-sonnet-5",reasoningLevel:"high",label:"Sonnet5: Track B inputs and report harness"})
]);
if(built.some(x=>x===null))throw new Error("Build or ingestion worker failed; inspect artifacts before execution");
phase("Verify");
const audit=await agent(common+`Independent correctness audit before full execution. Read CORE_HANDOFF.md/TRACK_B_HANDOFF.md/frozen RevB protocol and inspect actual core. Own independent tests and REVB_AUDIT.md only. Check exact KT against independent tiny reference both alphabets, 128-bit contexts, startup, checkpoints input order, forced disk spill equivalence, chunk boundaries, symbol attribution sum, occupancy reference, generators known entropy and PRNG freeze chronology, B source disjointness/control preservation. Run focused tests. Distinguish code bugs from finite sample reader limitations. Do not reject measured curves merely for contrary predictions. Return blockers and exact reproduction commands; no architecture essay. Build handoffs: ${JSON.stringify(built)}`,{model:"cpa/kimi-k3",reasoningLevel:"high",label:"KimiK3: independent correctness verification"});
phase("Execute Rev B");
const execution=await agent(common+`RESUMING A PRIOR RUN. Do NOT restart from scratch and do NOT recompute anything already done. First inspect ${args.storage}/revb_run/track_a/surfaces/ (and any track_b outputs) plus revb-terminal-status.json / revb-status.jsonl: a prior attempt already completed 24 of 90 Track A surfaces (G1 x5 seeds, G2 x5 seeds, G3(d=2) x5, G3(d=3) x5, G3(d=4) x4 seeds, i.e. it died mid-command on G3(d=4) seed 505) before the host daemon disconnected. Verify each existing surface file against the frozen execution-manifest hash and PROTOCOL/REVB_PROTOCOL, then resume strictly from the next unfinished item onward (G3(d=4) seed 505 first). Never overwrite or regenerate a verified, hash-matching completed surface.

STRICT RESOURCE DISCIPLINE, higher priority than wall-clock speed: this host is shared with other unrelated work and must not be saturated. Before every generate_corpus+kt_stream pair, check \`nproc\`, \`uptime\` (1-minute load average) and \`free -m\` (available memory). If load average exceeds the core count from \`nproc\`, or available memory is below 2 GiB, wait 60 seconds and recheck before starting that item; log every such pause with a timestamp and the readings to ${args.storage}/revb-resource-log.txt. Run exactly ONE generate_corpus+kt_stream pipeline at a time, never in parallel, even across independent generators or with Track B ingestion/scoring. Do not raise --cache-mib above the frozen value to go faster. Insert a short (5-10s) pause between finishing one surface and starting the next so the system settles. If the connection or host destabilizes again, stop cleanly, make sure the last fully-written surface file is intact (delete any partial/truncated one), and report the exact remaining item list and a resumable command rather than leaving corrupt state.

Integrate actual bugs found, log fixes without editing frozen protocol/kernels/thresholds. Finish reporting harness against actual core schema if necessary. Then continue executing the remaining Rev B items: 90A and 25B full length 2^23 each, all 12 checkpoints k0..16. Proceed with available tracks even if another input blocked; never fabricate missing surfaces. Use persistent bb terminal for long-running batch, remain responsible for completion rather than return 'started'. Cost characterize n,k,alphabet, extrapolate2^30 with disk/I/O assumptions. Full report from persisted raw arrays, all10 numeric predictions,3 gate checks with conditional interpretation, Annex diagnostics. Separability only correctness+foundation; preserve global bijection and report unavoidable invariance failure, don't invent corruption. If missing resources or runtime limit, record exact completed scope and resumable command; unfinished production is not scientific no-go. Copy user-facing report/raw-array archive/reusable source archive to origin storage. No busywork, prioritize actual run, but never at the cost of saturating the host. Audit: ${audit}`,{model:"claude-bridge/claude-sonnet-5",reasoningLevel:"high",label:"Sonnet5: resume execute90A+25B surfaces (throttled)"});
phase("Final audit");
return await agent(common+`Read-only final evidence audit (write REVB_FINAL_AUDIT.md only). Check actual results90A+25B at exact2^23 and checkpoints, provenance/freeze, rerun report computation from arrays (not reader), all10 numerical checks and3 gates, Annex separation, no cross-track claims, RAM proof/tests and measured costs, TrackB source eligibility/disjointness. Report missing scope plainly. Link final report and archive absolute paths. No additional scientific runs, scope expansion or unnecessary rewrite. Execution summary: ${execution}`,{model:"claude-bridge/claude-sonnet-5",reasoningLevel:"high",label:"Sonnet5: final evidence audit"});
