export const meta = {
  name: "block-01",
  description: "Frozen KT instrument: exact storage design, implementation, independent verification, full experiment and report",
  phases: [{title:"Exact storage design"},{title:"Implementation"},{title:"Independent checks and reporting"},{title:"Execute frozen experiment"},{title:"Final audit"}]
};
const common = `Work in the origin workspace. Read PROTOCOL.md completely; it is FROZEN before any sampling. User requests actual execution, not a proposal. Never alter generators/constants/thresholds to get good curves. No deployments/restarts/credential changes. Keep artifact outputs in the origin storage path provided below as well as source-local results when needed. Use only allocated role; do not spawn agents. Document all missing requirements honestly. Origin artifact directory: ${args.storage}. `;
phase("Exact storage design");
const design = await agent(common + `You own the most complicated part: exact KT streaming storage feasibility and mathematical audit. Inspect host resources. Design a practical one-pass-all-k engine with bounded RAM independent of N, exact counts, no eviction of information; disk may grow and must be reported. Consider disk-backed fixed cache, exact prefix tries or other bounded-memory external storage; characterize actual costs. Avoid a brute-force per-symbol SQLite transaction design that makes 5.1 billion context operations prohibitively slow if a better exact option is available. Do not generate any corpus. Write DESIGN.md specifying algorithm, API/build/test interfaces, PRNG specification and any unavoidable requirement contradictions. A growing in-memory map is NOT compliant, and an arbitrary max-N table is not a solution unless failure/noncompliance is explicit. A finite theoretical 32^16 bound must not be presented as practical constant RAM. Can offer fallback exact engine with explicit noncompliance only if needed, never silently. Check lag-copy entropy proof, G3 phase confound, permutation impossibility, negative normalization. Return concise implementation directions. Do not edit PROTOCOL.md.`, {model:"cpa/gpt-6-astra",reasoningLevel:"high",label:"Astra: exact storage and mathematical feasibility"});
phase("Implementation");
const implementation = await agent(common + `Read DESIGN.md. Implement generators, exact KT production engine and Python public availability(corpus_path,k_max)->array wrapper, reproducible build, reference small-data coder and focused tests. You own core source and generator implementation. Freeze machine-readable constants, seeds and specified PRNG implementation using SHA256 into immutable preregistration BEFORE any generator execution, including smoke samples. Write commands/interfaces into README.md. Aim to execute full 30 x 1e7 on this host with bounded RAM exact disk-backed counts if feasible. Never fake bounded memory or substitute estimator. Follow design and explain any necessary deviation. Verify no future leakage, initial prefixes, alphabet size32 even unused symbols, k16 requiring80-bit contexts, counts overflow, deterministic arithmetic order, prefix key collisions, streaming chunk boundaries. Correctness test fixtures may run after freeze. Do NOT run full production experiments yet; next agents audit first. Save implementation notes. Design summary: ${design}`, {model:"cpa/gpt-5.6-sol",reasoningLevel:"high",label:"Sol: implement and freeze engine"});
phase("Independent checks and reporting");
const checks = await parallel([
 () => agent(common + `Independently audit implementation against PROTOCOL.md and DESIGN.md. Own tests/independent* and AUDIT.md only, do not edit core. Run cheap executable tests using an independent reference, exhaustive tiny cases, known KT codes, no leakage, full80-bit contexts, bijection invariance, G1/G4 diagnostic logic and deterministic output. Check freeze chronology and analytical generator definitions, bounded RAM claim versus actual code. Report blockers with exact file locations and test results. Core summary: ${implementation}`, {model:"cpa/kimi-k3",reasoningLevel:"high",label:"Kimi K3: adversarial correctness tests"}),
 () => agent(common + `Own reporting/experiment orchestration scripts (not core source/tests). Read current interfaces and implement resumable sequential 30-run experiment orchestration, benchmark matrix over N and k, mean/std/min/max aggregation from saved arrays, all strict numeric predictions and seed-level checks, conditional separability gate, explicit diagnosis, Markdown cost/report and preferably simple SVG curves without raster image generation. Save exact raw arrays with constants/hashes/seeds and raw costs, never rederive curves for reporting. Full N=1e7 five seeds all six generators. Benchmarks can use N=1e4,1e5,1e6 at kmax=0,1,4,8,16 (different cost measurements clearly not altered experiment constants); resource estimates must reflect disk/index costs. No full production runs yet. Extrapolation1e9 must be labeled model not measurement; no-Go includes diagnostic failure, and separability impossible theorem must be documented. Do not edit frozen files. Write execution commands and report harness checks to REPORTING.md. Core summary: ${implementation}`, {model:"claude-bridge/claude-sonnet-5",reasoningLevel:"high",label:"Sonnet 5: experiment and reporting harness"})
]);
if (checks.some(x => x === null)) throw new Error("An independent check/harness worker failed; inspect before execution");
phase("Execute frozen experiment");
const execution = await agent(common + `Read all current files especially audits and reporting instructions. Integrate and fix actual code bugs (log fixes, NEVER change frozen definitions). Run entire test suite. Execute all30 production curves and cost benchmarks sequentially, respecting host safety (avoid OOM/disk exhaustion). Use persistent bb terminal for long experiments; wait via terminal commands, not shell sleeps or poll loops. Own integration and execution. You must not return 'started' as completion: remain responsible for terminal completion and persisted results, or report concrete resource/runtime blocker with remaining runs. Preserve full frozen N even if prediction failures occur; diagnostic checks on G1/G4 should distinguish implementation faults from regime mis-specification, no generator retuning. If full run too costly, gather bounded evidence, report incomplete scope and command to resume, never call resource failure corpus no-go. Generate final reports/artifacts in origin storage and source results; include reusable source archive. Independent outputs: ${JSON.stringify(checks)}`, {model:"cpa/gpt-5.6-sol",reasoningLevel:"high",label:"Sol: integrate, run30 curves, measure cost"});
phase("Final audit");
return await agent(common + `Perform final read-only completion audit against actual files, tests, runtime state and all requirements in PROTOCOL.md, not merely prior agent assertions. Verify count30 and N=1e7, hashes/seeds/raw arrays, recompute predictions from persisted arrays, entropy matching, benchmark/extrapolation validity, storage bound versus real engine, correct Go/diagnostic/no-go, separability gating. Run focused checks. Write FINAL_AUDIT.md and copy final user-facing report/artifacts to origin storage. Do not change thresholds or outputs to conceal failure. Return concise verified results, artifact absolute paths, remaining blockers and explicit incomplete deliverables if any. Execution summary: ${execution}`, {model:"claude-bridge/claude-sonnet-5",reasoningLevel:"high",label:"Sonnet 5: audit delivered evidence"});
